In [2]:
import geopandas as gpd 

mp = gpd.read_file("municipalities.geojson")

In [3]:
mp.head()

,adm3_name,adm3_name1,adm3_name2,adm3_name3,adm3_pcode,adm2_name,adm2_name1,adm2_name2,adm2_name3,adm2_pcode,...,area_sqkm,version,lang,lang1,lang2,lang3,adm3_ref_name,center_lat,center_lon,geometry
0,Abaqulusi,KZN263,None,None,ZA5263,Zululand,DC26,None,None,ZA526,...,4313.758286,v01,en,id,None,None,Abaqulusi,-27.807105,31.068011,"MULTIPOLYGON (((31.17994 -27.4445, 31.18019 -2..."
1,Alfred Duma,KZN238,None,None,ZA5238,Uthukela,DC23,None,None,ZA523,...,3764.472496,v01,en,id,None,None,Alfred Duma,-28.446155,29.899666,"MULTIPOLYGON (((29.75883 -28.15406, 29.76498 -..."
2,Amahlathi,EC124,None,None,ZA2124,Amathole,DC12,None,None,ZA212,...,4505.477231,v01,en,id,None,None,Amahlathi,-32.516105,27.389247,"MULTIPOLYGON (((27.57182 -32.19031, 27.5719 -3..."
3,Ba-Phalaborwa,LIM334,None,None,ZA9334,Mopani,DC33,None,None,ZA933,...,7489.282696,v01,en,id,None,None,Ba-Phalaborwa,-23.680560,31.330570,"MULTIPOLYGON (((31.53062 -23.21984, 31.53375 -..."
4,Beaufort West,WC053,None,None,ZA1053,Central Karoo,DC5,None,None,ZA105,...,21916.602218,v01,en,id,None,None,Beaufort West,-32.307385,22.608889,"MULTIPOLYGON (((22.62701 -31.82335, 22.63067 -..."

In [4]:
boundaries = gpd.read_file("zaf_adminboundaries_tabulardata.xlsx")

boundaries.head()

/home/joy/Downloads/gov_data/venv/lib/python3.14/site-packages/pyogrio/geopandas.py:382: UserWarning: More than one layer found in 'zaf_adminboundaries_tabulardata.xlsx': 'ADM0' (default), 'ADM1', 'ADM2', 'ADM3', 'ADM4'. Specify layer parameter to avoid this warning.
  result = read_func(

,ADM0_EN,ADM0_PCODE,ADM0_REF,ADM0ALT1_EN,ADM0ALT2_EN,DATE,VALIDON,VALIDTO,AREA_SQKM
0,South Africa,ZA,None,None,None,2018-12-27,2020-11-09,None,1220813.25

In [5]:
print(boundaries.columns)

Index(['ADM0_EN', 'ADM0_PCODE', 'ADM0_REF', 'ADM0ALT1_EN', 'ADM0ALT2_EN',
       'DATE', 'VALIDON', 'VALIDTO', 'AREA_SQKM'],
      dtype='str')

In [6]:
import pandas as pd 
boundaries_data = pd.read_excel("zaf_adminboundaries_tabulardata.xlsx",sheet_name=None)

In [18]:
df4 = boundaries_data["ADM3"]

"""I am assigning diff sheets into diff database, 
   so im able to clean and learn each sheet and its use

   return: (df4 which has teh square kilometers of each boundaries in each municipality)
"""

'I am assigning diff sheets into diff database, \n   so im able to clean and learn each sheet and its use\n\n   return: (df4 which has teh square kilometers of each boundaries in each municipality)\n'

In [14]:
df1 = boundaries_data["ADM0"]
"""
  returns: df1 contains the squared kilometers of the entire south africa(its boundaries)

"""

'\n  returns: df1 contains the squared kilometers of the entire south africa(its boundaries)\n\n'

In [15]:
df2 = boundaries_data["ADM1"]
""" 
  returns: df2 contains the square kilometers of each provinces (its boundaries)
"""

' \n  returns: df2 contains the square kilometers of each provinces (its boundaries)\n'

In [19]:
df3 = boundaries_data["ADM2"]
""" 
  returns: df3 contains district boundaries in square kilometeres 

"""

' \n  returns: df3 contains district boundaries in square kilometeres \n\n'

In [22]:
df5 = boundaries_data["ADM4"]
"""
returns: df5 containing the local units like the wards for a village/town in square kilometers 

"""

'\nreturns: df5 containing the local units like the wards for a village/town in square kilometers \n\n'

In [ ]:
df4.drop(columns = ["ADM3_REF","ADM3ALT1_EN","ADM3ALT2_EN","VALIDTO"])
""" 
i removed columns that have no use and conatined nan values
"""

Index(['ADM3_EN', 'ADM3_PCODE', 'ADM2_EN', 'ADM2_PCODE', 'ADM1_EN',
       'ADM1_PCODE', 'ADM0_EN', 'ADM0_PCODE', 'DATE', 'VALIDON', 'ADM1_ID',
       'ADM2_ID', 'ADM3_ID', 'AREA_SQKM'],
      dtype='str')

In [64]:
df4.head()

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,DATE,VALIDON,ADM1_ID,ADM2_ID,ADM3_ID,AREA_SQKM
0,Abaqulusi,ZA5263,Zululand,ZA526,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC26,KZN263,4313.758169
1,Alfred Duma,ZA5238,Uthukela,ZA523,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC23,KZN238,3764.472440
2,Amahlathi,ZA2124,Amathole,ZA212,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC12,EC124,4505.477351
3,Ba-Phalaborwa,ZA9334,Mopani,ZA933,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC33,LIM334,7489.278232
4,Beaufort West,ZA1053,Central Karoo,ZA105,Western Cape,ZA1,South Africa,ZA,2018-12-27,2020-11-09,WC,DC5,WC053,21916.602981

In [ ]:
df2 = df2.drop_duplicates()
""" 
removed duplicates for df2
"""

' \nremoved duplicates\n'

In [43]:
df3 = df3.drop_duplicates()
""" 
removed duplicates for df3
"""

' \nremoved duplicates for df3\n'

In [45]:
df4.drop_duplicates()
""" 
removed duplicates for df4
"""

' \nremoved duplicates for df4\n'

In [ ]:
# Now lets remove useless colunms so it will make sense!!

df1 = df1.drop(columns = ["ADM0_REF", "ADM0ALT1_EN", "ADM0ALT2_EN", "VALIDTO"])

        ADM0_EN ADM0_PCODE       DATE    VALIDON   AREA_SQKM
0  South Africa         ZA 2018-12-27 2020-11-09  1220813.25

In [59]:
df1.head()

        ADM0_EN ADM0_PCODE       DATE    VALIDON   AREA_SQKM
0  South Africa         ZA 2018-12-27 2020-11-09  1220813.25

In [53]:
df2 = df2.drop(columns = ["ADM1_ID.2","ADM1_ID.3", "ADM1_ID.4","ADM1_ID.9"])

In [60]:
df2.head()

,ADM1_ID,ADM1_ID.1,ADM1_ID.5,ADM1_ID.6,ADM1_ID.7,ADM1_ID.8,ADM1_ID.10,AREA_SQKM
0,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,ADM1_ID,168965.984375
1,Free State,ZA4,South Africa,ZA,2018-12-27,2020-11-09,ADM1_ID,129825.164062
2,Gauteng,ZA7,South Africa,ZA,2018-12-27,2020-11-09,ADM1_ID,18178.308594
3,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,ADM1_ID,94361.328125
4,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,ADM1_ID,125754.507812

In [56]:
df3 = df3.drop(columns = ["ADM2_REF", "ADM2ALT1_EN", "ADM2ALT2_EN", "VALIDTO"])

In [61]:
df3.head()

,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,DATE,VALIDON,ADM1_ID,ADM2_ID,AREA_SQKM
0,Alfred Nzo,ZA244,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC44,10731.218750
1,Amajuba,ZA525,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC25,7102.421875
2,Amathole,ZA212,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC12,21117.166016
3,Bojanala,ZA637,North West,ZA6,South Africa,ZA,2018-12-27,2020-11-09,NW,DC37,18333.390625
4,Buffalo City,ZA292,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,BUF,2750.282715

In [ ]:
#Already cleaned this sheet on the previous cells
df4.head()

,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,DATE,VALIDON,ADM1_ID,ADM2_ID,ADM3_ID,AREA_SQKM
0,Abaqulusi,ZA5263,Zululand,ZA526,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC26,KZN263,4313.758169
1,Alfred Duma,ZA5238,Uthukela,ZA523,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC23,KZN238,3764.472440
2,Amahlathi,ZA2124,Amathole,ZA212,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC12,EC124,4505.477351
3,Ba-Phalaborwa,ZA9334,Mopani,ZA933,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC33,LIM334,7489.278232
4,Beaufort West,ZA1053,Central Karoo,ZA105,Western Cape,ZA1,South Africa,ZA,2018-12-27,2020-11-09,WC,DC5,WC053,21916.602981

In [ ]:
df5 = df5.drop(columns = ["ADM4_REF", "ADM4ALT1_EN","ADM4ALT2_EN","VALIDTO"])

In [84]:
df5.head()

,ADM4_PCODE,ADM3_EN,ADM3_PCODE,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,DATE,VALIDON,ADM1_ID,ADM2_ID,ADM3_ID,AREA_SQKM
0,ZA9344001,Makhado,ZA9344,Vhembe,ZA934,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC34,LIM344,19.005403
1,ZA9344002,Makhado,ZA9344,Vhembe,ZA934,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC34,LIM344,10.337720
2,ZA9344003,Makhado,ZA9344,Vhembe,ZA934,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC34,LIM344,44.084492
3,ZA9344004,Makhado,ZA9344,Vhembe,ZA934,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC34,LIM344,15.263188
4,ZA9344005,Makhado,ZA9344,Vhembe,ZA934,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC34,LIM344,106.844335

In [66]:
# Let us now rename the columns to be easily interpreted

df1 = df1.rename(columns= {
    "ADM0_EN": "Country_name",
    "ADM0_PCODE" : "Country_code",
    "VALIDON" : "Valid_from"
})

In [67]:
df1

   Country_name Country_code       DATE Valid_from   AREA_SQKM
0  South Africa           ZA 2018-12-27 2020-11-09  1220813.25

In [70]:
df2 = df2.rename(columns= {
    "ADM1_ID" : "Province_name",
    "ADM1_ID.1" : "Province_ID",
    "ADM1_ID.5" : "Country",
    "ADM1_ID.6": "Country_code",
    "ADM1_ID.7" : "Valid_from",
    "ADM1_ID.8" : "Valid_to"

})

In [71]:
df2 = df2.drop(columns=["ADM1_ID.10"] )

In [72]:
df2.head()

,Province_name,Province_ID,Country,Country_code,Valid_from,Valid_to,AREA_SQKM
0,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,168965.984375
1,Free State,ZA4,South Africa,ZA,2018-12-27,2020-11-09,129825.164062
2,Gauteng,ZA7,South Africa,ZA,2018-12-27,2020-11-09,18178.308594
3,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,94361.328125
4,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,125754.507812

In [75]:
df3 = df3.rename(columns = {
    "ADM2_EN" : "District_name",
    "ADM2_PCODE" : "District_code",
    "ADM1_EN" : "Province",
    "ADM1_PCODE" : "Province_code",
    "ADM0_EN" : "Country",
    "ADM0_PCODE" : "Country_code",
    "VALIDON" : " Valid_from",
    "ADM1_ID" : "Province_ID",
    "ADM2_ID" : "District_ID"

})

In [76]:
df3.head()

,District_name,District_code,Province,Province_code,Country,Country_code,DATE,Valid_from,Province_ID,District_ID,AREA_SQKM
0,Alfred Nzo,ZA244,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC44,10731.218750
1,Amajuba,ZA525,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC25,7102.421875
2,Amathole,ZA212,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC12,21117.166016
3,Bojanala,ZA637,North West,ZA6,South Africa,ZA,2018-12-27,2020-11-09,NW,DC37,18333.390625
4,Buffalo City,ZA292,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,BUF,2750.282715

In [78]:
df4 = df4.rename(columns= {
    "ADM3_EN" : "Municipality_name",
    "ADM3_PCODE" : "Municipal_code",
    "ADM2_EN" : "District",
    "ADM2_PCODE" : " District_code",
    "ADM1_EN" : 'Province',
    "ADM1_PCODE" : "Province_code",
    "ADM0_EN" : "Country",
    "ADM0_PCODE" : "Country_code",
    "VALIDON" : "Valid_from",
    "AMD1_ID" : "Province_ID",
    "ADM2_ID" : "District_ID",
    "ADM3_ID" : "Municipality_ID"
})

In [79]:
df4.head()

,Municipality_name,Municipal_code,District,District_code,Province,Province_code,Country,Country_code,DATE,Valid_from,ADM1_ID,District_ID,Municipality_ID,AREA_SQKM
0,Abaqulusi,ZA5263,Zululand,ZA526,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC26,KZN263,4313.758169
1,Alfred Duma,ZA5238,Uthukela,ZA523,KwaZulu-Natal,ZA5,South Africa,ZA,2018-12-27,2020-11-09,KZN,DC23,KZN238,3764.472440
2,Amahlathi,ZA2124,Amathole,ZA212,Eastern Cape,ZA2,South Africa,ZA,2018-12-27,2020-11-09,EC,DC12,EC124,4505.477351
3,Ba-Phalaborwa,ZA9334,Mopani,ZA933,Limpopo,ZA9,South Africa,ZA,2018-12-27,2020-11-09,LIM,DC33,LIM334,7489.278232
4,Beaufort West,ZA1053,Central Karoo,ZA105,Western Cape,ZA1,South Africa,ZA,2018-12-27,2020-11-09,WC,DC5,WC053,21916.602981

In [88]:
df5 = df5.rename(columns = {
    "ADM4_PCODE" : "Local_unit_code",
    "ADM3_EN" : "Municipality",
    "ADM2_PCODE" : "Municpal_code",
    "ADM2_EN" : "District",
    "ADM2_PCODE" : "District_code",
    "ADM1_EN" : "Province",
    "ADM1_PCODE" : "Provincal_code",
    "ADM0_EN" : "Country",
    "ADM0_PCODE" : "Country_code"



})

In [90]:
df5 = df5.rename(columns = {

    "ADM3_PCODE" : "Municipal_code"
    })

In [ ]:
DF5 = df5.drop(columns = ["ADM1_ID", "ADM2_ID", "ADM3_ID"])

In [94]:
df5 =DF5