In [1]:
import pandas as pd
df = pd.read_excel("Population data.ods",engine="odf")

In [2]:
df.to_excel("Population_data.xlsx")

In [6]:
df1= pd.read_excel("Population_data.xlsx")

In [22]:
df1.columns

Index(['Unnamed: 0', 'Rank', 'Urban city', 'Population'], dtype='str')

In [24]:
df1 =  df1.drop(columns =['Unnamed: 0'] )

In [25]:
df1

    Rank     Urban city  Population
0      1  Johannesburg      7077175
1      2     Cape Town      4508921
2      3        Durban      3177927
3      4      Pretoria      1836166
4      5       Klipgat      1300816
..   ...            ...         ...
65    66      Mankweng        69995
66    67      Khutsong        69746
67    68  Modderspruit        68683
68    69      Makhanda        67923
69    70   Piet Retief        67291

[70 rows x 3 columns]

In [26]:
df1.drop_duplicates()

    Rank     Urban city  Population
0      1  Johannesburg      7077175
1      2     Cape Town      4508921
2      3        Durban      3177927
3      4      Pretoria      1836166
4      5       Klipgat      1300816
..   ...            ...         ...
65    66      Mankweng        69995
66    67      Khutsong        69746
67    68  Modderspruit        68683
68    69      Makhanda        67923
69    70   Piet Retief        67291

[70 rows x 3 columns]